### ISSUE TITLE
How to change Raft node list

### ISSUE THREAD

**Issue by krishnanandnb** [github/freno#146]
Hi folks
In the raft node list, it is mentioned that the list is static. How to dynamically add IP addresses to the raft node list .

**Comment by shlomi-noach** [comment]
Unfortunately the static nature of the list means you cannot add IPs dynamically. It is only by changing configuration, which requires an incremental rollout, one by one, for all raft members.

**Comment by timvaillancourt** [comment]
> Thanks for the quick reply @shlomi-noach in environments like Kubernetes what is the recommended solution as Pods (nodes) can change dynamically? Also if we change the configuration will it get refreshed dynamically ?

@krishnanandnb in a Kubernetes deployment you'll need a process (perhaps a "sidecar") to update the Freno configuration and restart the nodes. I suggest that this automation checks if there is a healthy leader before restarting 👍

**Comment by krishnanandnb** [comment]
Thanks so much @timvaillancourt maybe using mysql for HA will solve some complexities instead of raft ?

**Comment by dm-2** [comment]
@krishnanandnb we run freno on VMs with fixed IPs internally, which might be an option to consider.

I'll close this issue for now as we have no plans to add support for a dynamic raft node list, feel free to re-open if you want to discuss further 🙂
